In [59]:
import numpy as np

In [60]:
my_list = [1,2,3,4,5,6]

In [61]:
np.array(my_list)

array([1, 2, 3, 4, 5, 6])

In [62]:
nested_list = [[1,2],[2,3],[4,5]]

In [63]:
np.array(nested_list)

array([[1, 2],
       [2, 3],
       [4, 5]])

In [64]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [66]:
np.zeros(4)

array([0., 0., 0., 0.])

In [67]:

np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
np.ones(3)

array([1., 1., 1.])

In [69]:

np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

In [71]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [72]:

r = np.random.rand(2)

In [73]:
print(r)

[0.02058449 0.96990985]


In [74]:
np.random.rand(4, 5)

array([[0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224],
       [0.52475643, 0.43194502, 0.29122914, 0.61185289, 0.13949386],
       [0.29214465, 0.36636184, 0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041, 0.60754485, 0.17052412]])

In [75]:
np.random.randn(5,5)

array([[-0.60063869, -0.29169375, -0.60170661,  1.85227818, -0.01349722],
       [-1.05771093,  0.82254491, -1.22084365,  0.2088636 , -1.95967012],
       [-1.32818605,  0.19686124,  0.73846658,  0.17136828, -0.11564828],
       [-0.3011037 , -1.47852199, -0.71984421, -0.46063877,  1.05712223],
       [ 0.34361829, -1.76304016,  0.32408397, -0.38508228, -0.676922  ]])

In [76]:
np.random.randint(0,100)

87

In [77]:
np.random.randint(1,100,10)

array([63, 11, 81,  8, 35, 35, 33,  5, 41, 28])

In [78]:
np.random.randint(1,100,(5,6))

array([[ 7, 73, 72, 12, 34, 33],
       [48, 23, 62, 88, 37, 99],
       [44, 86, 91, 35, 65, 99],
       [47, 78,  3,  1,  5, 90],
       [14, 27,  9, 79, 15, 90]])

In [79]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [80]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [81]:
arr = np.arange

In [82]:
arr

<function numpy.arange>

In [83]:
ranarr = np.random.randint(0,50,10)

In [84]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [92]:
arr.shape

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

In [87]:
arr.reshape(5,5)

AttributeError: 'builtin_function_or_method' object has no attribute 'reshape'

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.reshape(3,6)

ValueError: cannot reshape array of size 25 into shape (3,6)

In [50]:
ranarr.max()

39

In [51]:
ranarr.argmax()

7

In [52]:
ranarr.min()

2

In [53]:
ranarr.max()

39

In [55]:

ranarr.argmin()

9

In [57]:
arr.dtype

dtype('int64')

In [58]:
ranarr.dtype

dtype('int64')