In [54]:
import numpy as np

In [55]:
arr = np.arange(0,11)

In [56]:
arr[8]

8

In [57]:
arr[2:5]

array([2, 3, 4])

In [58]:
arr[2:11:3]

array([2, 5, 8])

In [59]:
arr[:11:3]

array([0, 3, 6, 9])

In [60]:
# BROADCASTING

In [61]:
# Write a python function to convert celcius to fareghnite  values
def celcius_to_fareghnite(celcius):
    return celcius * 1.8 + 32

In [62]:
celcius_to_fareghnite(58)

136.4

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr[0:5] = 100

In [65]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [66]:
arr_list = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]

In [67]:
arr_list[0] = 100

In [68]:
arr_list

[100, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [69]:
arr = np.arange(0,11)

In [70]:
slice_of_arr = arr

In [71]:
slice_of_arr[:] = 99

In [72]:
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [73]:
new_arr = arr.copy()

In [74]:
new_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [75]:

new_arr[:] = 150

In [76]:
new_arr

array([150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150])

In [77]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [78]:
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [79]:
sec_arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [80]:
sec_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
sec_arr[0]

array([1, 2, 3])

In [82]:
sec_arr[1][1]

5

In [83]:
sec_arr[1,1]

5

In [84]:
# SLICING

In [85]:
sec_arr[1:2]

array([[4, 5, 6]])

In [86]:
sec_arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
sec_arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [88]:
arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [89]:
arr_new = np.arange(0,16)

In [90]:
arr_new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [91]:
test_arr = arr_new > 4

In [92]:
test_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [93]:
arr_new[test_arr]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [94]:
arr[arr>4]

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])